learn about numby with chai aur code


## Arrays--

In [136]:
import numpy as np
import time as t

In [137]:
arr_id1=np.array([1,2,3,4,5])
print("1D Array: ",arr_id1)

1D Array:  [1 2 3 4 5]


In [138]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D Array is", arr_2d)

2D Array is [[1 2 3]
 [4 5 6]]


### List vs numpy Array

In [139]:
list=[1,2,3,4]
print(f" List in Python {list*4}")

np_array=np.array([6,7,8,9])  #Element wise multiplication
print(f"Python Array Multiplication {np_array*2}")

start=t.time()
list=[i*2 for i in range(1000000)]
print("\n List operation time: ",t.time()-start)


start=t.time()
np_array=np.arange(1000000) * 2
print("\n Numpy  operation time: ",t.time()-start)

 List in Python [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
Python Array Multiplication [12 14 16 18]

 List operation time:  0.04575514793395996

 Numpy  operation time:  0.0053479671478271484


In [140]:
## Creating Array from Scratch

In [141]:
zeros=np.zeros((3,4))
print("zeros Array: \n", zeros)

zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [142]:
ones=np.ones((2,3))
print("Ones Array:\n",ones)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [143]:
full=np.full((2,2),7)
print("Full Arrays:\n",full)



random=np.random.random((2,3))
print(f"Random Arrays:\n {random}")

sequence=np.arange(0,10,2)
print("Sequence Array:\n",sequence)

Full Arrays:
 [[7 7]
 [7 7]]
Random Arrays:
 [[0.93291815 0.47790836 0.57584694]
 [0.40440189 0.82351349 0.08749514]]
Sequence Array:
 [0 2 4 6 8]


## Vector,Matrix Tensor


In [144]:
vector=np.array([1,2,3])
print("Vector:",vector)


matrix=np.array([[1,2,3],[4,5,6]])
print("matrix: \n",matrix)

tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor:\n ",tensor)

Vector: [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [145]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape ",arr.shape)
print("Dimension ",arr.ndim)
print("Size ",arr.size)
print("DType ",arr.dtype)


Shape  (2, 3)
Dimension  2
Size  6
DType  int64


## Array Reshapping

In [153]:
arr=np.arange(12)
print("Original Array ",arr)
reshaped=arr.reshape((3,4))
print("\n Reshaped Array", reshaped)

flattend=reshaped.flatten()
print("\n Flattened Array: ",flattend)

#ravel(returns view,instead of copy)
raveled =reshaped.ravel()
print("\n Raveled Array: ",raveled)

#Transpose
transpose=reshaped.T
print("Transpose matrix: ",transpose)


# arr=np.arange(2,12,2)
# print("Array: ",arr)

Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose matrix:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
