learn about numby with chai aur code


## Arrays--

In [113]:
import numpy as np
import time as t

In [114]:
arr_id1=np.array([1,2,3,4,5])
print("1D Array: ",arr_id1)

1D Array:  [1 2 3 4 5]


In [115]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D Array is", arr_2d)

2D Array is [[1 2 3]
 [4 5 6]]


### List vs numpy Array

In [116]:
list=[1,2,3,4]
print(f" List in Python {list*4}")

np_array=np.array([6,7,8,9])  #Element wise multiplication
print(f"Python Array Multiplication {np_array*2}")

start=t.time()
list=[i*2 for i in range(1000000)]
print("\n List operation time: ",t.time()-start)


start=t.time()
np_array=np.arange(1000000) * 2
print("\n Numpy  operation time: ",t.time()-start)

 List in Python [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
Python Array Multiplication [12 14 16 18]

 List operation time:  0.07624983787536621

 Numpy  operation time:  0.005562305450439453


In [117]:
## Creating Array from Scratch

In [118]:
zeros=np.zeros((3,4))
print("zeros Array: \n", zeros)

zeros Array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [119]:
ones=np.ones((2,3))
print("Ones Array:\n",ones)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [120]:
full=np.full((2,2),7)
print("Full Arrays:\n",full)



random=np.random.random((2,3))
print(f"Random Arrays:\n {random}")

sequence=np.arange(0,10,2)
print("Sequence Array:\n",sequence)

Full Arrays:
 [[7 7]
 [7 7]]
Random Arrays:
 [[0.4385247  0.89582539 0.43356413]
 [0.13089459 0.89779029 0.217201  ]]
Sequence Array:
 [0 2 4 6 8]
