## Numpy Array operations 

In [150]:
import numpy as np

## Indexing and Slicing

In [151]:
arr=np.arange(1,11)
print("array: ",arr)
print(type(arr))
print("Basic Slicing", arr[2:7])
print("Negative indexing", arr[-3])

array:  [ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
Basic Slicing [3 4 5 6 7]
Negative indexing 8


In [152]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("2D Array is", arr_2d)
print("basic Slicing", arr_2d[1, 2])
print("basic Slicing", arr_2d[2, 2])
print("Entire Row ",arr_2d[1])
print("Entire Column ",arr_2d[:,0])

2D Array is [[1 2 3]
 [4 5 6]
 [7 8 9]]
basic Slicing 6
basic Slicing 9
Entire Row  [4 5 6]
Entire Column  [1 4 7]


## Sorting


In [153]:
unsorted=np.array([3,2,1,8,6,2,5])
print("Unsorted Array is: ",unsorted)
print("Sorted Array is : ",np.sort(unsorted))

arr_2d=np.array([[3,1], [1,2], [2,3]])
print("Unsorted :",arr_2d)
print("Column by Sorted: ",np.sort(arr_2d, axis=0))
print("Row by Sorted: ",np.sort(arr_2d, axis=1))

Unsorted Array is:  [3 2 1 8 6 2 5]
Sorted Array is :  [1 2 2 3 5 6 8]
Unsorted : [[3 1]
 [1 2]
 [2 3]]
Column by Sorted:  [[1 1]
 [2 2]
 [3 3]]
Row by Sorted:  [[1 3]
 [1 2]
 [2 3]]


## Filter


In [154]:
num=np.arange(1,11)
print("Original Number: ",num)
even_num=num[num %2==0]
print("Even Numbers", even_num)

Original Number:  [ 1  2  3  4  5  6  7  8  9 10]
Even Numbers [ 2  4  6  8 10]


 ## Filter With Mask

In [155]:
mask=num > 5
print("Number is greater than 5 ", num[mask])


Number is greater than 5  [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [ ]:
indices=[0,2,4]
print(num[indices])

where_result=np.where(num > 5)
print("NP where ", num[where_result])


where_ev=np.where(num %2==0)
print("Even ",where_ev)

[1 3 5]
NP where  [ 6  7  8  9 10]
